version: "3.5"
services:
  webserver:
    networks:
      dev_docker_bitpanda:
        ipv4_address: 177.123.179.1
    image: nginx:alpine
    container_name: bitpanda-webserver
    working_dir: /application
    tty: true
    environment:
      - TERM=xterm-256color
    volumes:
      - .:/application
      - ./storage/app/public:/application/public/storage:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/ssl
    ports:
      - "80"
      - "443"
    depends_on:
      - php-fpm
    restart: unless-stopped

  php-fpm:
    networks:
      dev_docker_bitpanda:
        ipv4_address: 177.123.179.2
    build: docker/php-fpm
    container_name: bitpanda-php-fpm
    tty: true
    environment:
      - TERM=xterm-256color
      - XDEBUG_CONFIG=remote_host=172.17.0.1
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    restart: unless-stopped

  mysql-bitpanda:
    networks:
      dev_docker_bitpanda:
        ipv4_address: 177.123.179.3
    image: mariadb:10.4
    container_name: mysql-bitpanda
    working_dir: /application
    volumes:
      - .:/application
      - ./mysql/storage/bitpanda:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=1234abcD
      - MYSQL_USER=bitpanda
      - MYSQL_PASSWORD=1234abcD
      - TERM=xterm-256color
    ports:
      - "3306"


networks:
  dev_docker_bitpanda:
    name: bitpanda_default
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "177.123.179.0/16"
